import keyMirror from 'keymirror'

export default keyMirror ({
FETCH_CONTACTS_SUCCESS: null,
FETCH_CONTACTS_ERROR: null,
FETCH_PAGES_SUCCESS: null,
FETCH_PAGES_ERROR: null,
FETCH_ARTICLES_SUCCESS: null,
FETCH_ARTICLES_ERROR: null,
FETCH_PHOTOGALLERY_SUCCESS: null,
FETCH_PHOTOGALLERY_ERROR: null,
FETCH_COMMENTS_SUCCESS: null,
FETCH_COMMENTS_ERROR: null,
FETCH_COMMENT_ADD: null,
FETCH_MENU_ERROR: null,
FETCH_MENU_SUCCESS: null,
ADD_NEW_MESSAGE: null,
FETCH_MAIN_SUCCESS: null,
FETCH_MAIN_ERROR: null,
RECIVE_WIDGET: null,
})